# ~/.config/wallust/templates/wallust.toml

backend = "wal"
palette = "light16"
threshold = 20
color_space = "lch"

[templates]
code       = { src = "code-light.template",     dst = "~/.config/Code/User/settings.json" }
css        = { src = "color.template",          dst = "~/.config/YASD/color.css" }
fastfetch  = { src = "fastfetch.template",      dst = "~/.config/fastfetch/config.jsonc" }
hyprland  =  { src = "color-hyprland.template", dst = "~/.config/hypr/conf/colors.conf" }
kdeglobals = { src = "kdeglobals.template",     dst = "~/.config/kdeglobals" }
kitty      = { src = "kitty.template",          dst = "~/.config/kitty/theme.conf" }
kvantum    = { src = "kvantum-light.template",  dst = "~/.config/Kvantum/MateriaLight/MateriaLight.kvconfig" }
mako       = { src = "mako.template",           dst = "~/.config/mako/config" }
niri       = { src = "niri.template",           dst = "~/.config/niri/conf/color.kdl"}
rofi       = { src = "rofi-theme.template",     dst = "~/.config/rofi/theme.rasi" }
spotify    = { src = "spotify.template",        dst = "~/.config/spicetify/Themes/SeraDOTS/color.ini" }
sway       = { src = "swayfx-theme.template",   dst = "~/.config/sway/config.d/theme.conf" }
swaylock   = { src = "swaylock.template",       dst = "~/.config/swaylock/config" }
vencord    = { src = "vencord.template",        dst = "/home/amelie/.config/vesktop/settings/quickCss.css" }
